#!/usr/bin/env python3
"""Deterministic issue automation fixture; no provider calls or API credentials."""
import json
import re
import sys
from pathlib import Path

current = None
step = 0


def send(value):
    print(json.dumps(value), flush=True)


def tool(name, args):
    return '```hivemind-tool\n' + json.dumps({'name': name, 'args': args}) + '\n```'


for line in sys.stdin:
    frame = json.loads(line)
    kind = frame.get('type')
    if kind == 'prompt':
        message = frame.get('message', '')
        matches = re.findall(r'generated by Hivemind for task (tk_\w+);[^\n]*\nYour role: (\w+)\.', message)
        if matches and matches[-1] != current:
            current = matches[-1]
            step = 0
        role = current[1] if current else ''
        text = 'done'
        if step == 0 and role == 'plan':
            text = tool('tasks.plan.propose', {'tasks': [{
                'key': 'fix', 'objective': 'Implement fixture fix',
                'acceptance': ['The fixture file exists'], 'capabilities': ['backend'],
                'owner': 'Engineer', 'reviewer': 'Reviewer',
            }]})
        elif step == 0 and role == 'work':
            if 'Preserve session handling.' not in message or 'Do not change existing endpoints.' not in message:
                text = tool('tasks.block', {'reason': 'Issue description or discussion missing from worker context'})
            else:
                Path('fixture-result.txt').write_text('Issue description and discussion reached the worker.\n')
                text = tool('tasks.result.submit', {
                    'summary': 'Fixture fix implemented',
                    'artifacts': [{'kind': 'file', 'reference': 'fixture-result.txt', 'description': 'Verified issue context'}],
                    'verification': [{'check': 'file exists', 'outcome': 'passed', 'detail': str(Path('fixture-result.txt').is_file())}],
                })
        elif step == 0 and role == 'review':
            text = tool('tasks.review', {'verdict': 'approve', 'notes': 'Fixture criteria met'})
        step += 1
        send({'type': 'response', 'command': 'prompt', 'success': True})
        send({'type': 'message_end', 'message': {'role': 'assistant', 'content': [{'type': 'text', 'text': text}],
              'usage': {'input': 1, 'output': 1, 'cacheRead': 0, 'cacheWrite': 0, 'totalTokens': 2}}})
        send({'type': 'agent_settled'})
    elif kind == 'get_session_stats':
        send({'type': 'response', 'command': kind, 'success': True, 'data': {'contextUsage': {'tokens': 1}}})
    else:
        send({'type': 'response', 'command': kind, 'success': True})
