#!/usr/bin/env python3
"""Scripted stand-in for the Pi RPC runtime, for UI development and screenshots.

Hivemind spawns this exactly like `pi --mode rpc --no-session ...`. It never
contacts a model: chat prompts get short canned replies, and coordination
prompts (task rooms) walk the plan/work/review steps with hivemind-tool calls.
"""
import json, os, random, re, sys, time

args = sys.argv[1:]
system = args[args.index("--append-system-prompt") + 1] if "--append-system-prompt" in args else ""
match = re.search(r"You are the (\w+)", system)
persona = match.group(1) if match else "Agent"
delay = float(os.environ.get("FAKE_PI_DELAY", "1.2"))
tokens = 0

CHAT = {
    "Engineer": [
        "I'd keep the change small: add the endpoint behind the existing router and cover it with one integration test.",
        "Agreed. I can wire the handler now and leave the validation rules to the shared schema.",
        "The failing case is an empty body; I'll return 400 with the standard error shape.",
    ],
    "Reviewer": [
        "Looks reasonable. Watch the error path: internal failures should stay sanitized.",
        "One concern: the session rotation should happen before the next prompt, not mid-turn.",
        "Approve from my side once the test covers the empty-body case.",
    ],
}


def send(frame):
    sys.stdout.write(json.dumps(frame) + "\n")
    sys.stdout.flush()


def tool(name, args):
    return "```hivemind-tool\n" + json.dumps({"name": name, "args": args}) + "\n```"


def between(text, start, end):
    i = text.rfind(start)
    rest = text[i + len(start):] if i >= 0 else text
    j = rest.find(end)
    return rest[:j] if j >= 0 else rest


def answer(prompt):
    if "tool result:" in prompt[:300].lower():
        return "Done."
    if "generated by Hivemind for task " in prompt:
        role = between(prompt, "Your role: ", ".")
        if role == "plan":
            # Creating an issue with no sub-issues asks the coordinator to plan
            # them. This stand-in always does, so the demo shows child issues
            # appearing on their own.
            return tool("tasks.plan.propose", {
                "tasks": [
                    {
                        "key": "api",
                        "objective": "Implement the backend for this issue",
                        "acceptance": ["backend behavior matches the issue"],
                        "capabilities": ["backend"],
                    },
                    {
                        "key": "ui",
                        "objective": "Implement the frontend for this issue",
                        "acceptance": ["frontend behavior matches the issue"],
                        "capabilities": ["frontend"],
                        "depends_on": ["api"],
                    },
                ],
            })
        if role == "work":
            return tool("tasks.result.submit", {
                "summary": "Implemented and verified the change.",
                "artifacts": [{"kind": "file", "reference": "notes.md", "description": "what changed"}],
                "verification": [{"check": "unit tests", "outcome": "passed", "detail": "12 passed"}],
            })
        if role == "review":
            return tool("tasks.review", {"verdict": "approve", "notes": "Acceptance criteria met."})
        return "Done."
    lines = CHAT.get(persona, ["Noted."])
    return random.choice(lines)


for line in sys.stdin:
    try:
        frame = json.loads(line)
    except ValueError:
        continue
    kind = frame.get("type")
    if kind == "prompt":
        message = frame.get("message", "")
        send({"type": "response", "command": "prompt", "success": True})
        time.sleep(delay)
        text = answer(message)
        tokens += len(message) // 4 + len(text) // 4
        send({"type": "message_end", "message": {"role": "assistant", "content": [{"type": "text", "text": text}],
              "usage": {"input": len(message) // 4, "output": len(text) // 4, "cacheRead": 0, "cacheWrite": 0, "totalTokens": len(message) // 4 + len(text) // 4}}})
        send({"type": "agent_settled"})
    elif kind == "get_session_stats":
        send({"type": "response", "command": "get_session_stats", "success": True, "data": {"contextUsage": {"tokens": tokens}}})
    else:
        send({"type": "response", "command": kind, "success": True})
