#!/usr/bin/env bash
# Run a throwaway Hivemind (API + web UI) isolated from your real/production one.
#   scripts/dev-sandbox.sh              # open the UI at http://127.0.0.1:5174 (API on :7575, not 7474)
#   scripts/dev-sandbox.sh --api-only   # API only; http://127.0.0.1:7575 is JSON, not a web page
#   scripts/dev-sandbox.sh --reset      # wipe sandbox config, data and workspace, then start fresh
#   DEV_PORT=7600 DEV_UI_PORT=5200 scripts/dev-sandbox.sh
#
# Safe to re-run: the sandbox is created once and then reused (config, data, workspace).
# Everything lives in $DEV_HOME (default ~/.cache/hivemind-dev); the repo's hivemind.toml
# and .hivemind/ are never touched. It must be OUTSIDE any git repo because OpenCode hides
# its free `opencode/*` models for agents whose workspace is inside one.
#
# Runtime for the two sandbox agents (DEV_RUNTIME overrides the choice):
#   opencode  (default when installed) with the first two free `opencode/*-free` models
#   pi | omp  uses that runtime's own default model
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
. "$root/scripts/js-pm.sh"

port=${DEV_PORT:-7575}
ui_port=${DEV_UI_PORT:-5174}
home=${DEV_HOME:-${XDG_CACHE_HOME:-$HOME/.cache}/hivemind-dev}
workspace=$home/workspace
config=$home/hivemind.toml
ui=1
for arg in "$@"; do
  case "$arg" in
    --api-only) ui=0 ;;
    --ui) ui=1 ;;
    --reset)
      # Refuse anything that is not clearly a sandbox dir.
      case "$home" in ""|/|"$HOME"|"$root") echo "refusing to reset $home" >&2; exit 2 ;; esac
      rm -rf "$home" ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing required tool: $1 ($2)" >&2; exit 1; }; }
[ -n "${HIVEMIND_BIN:-}" ] || need cargo "install Rust from https://rustup.rs"
if [ "$ui" = 1 ]; then select_js_pm; fi

mkdir -p "$workspace"
if git -C "$workspace" rev-parse --git-dir >/dev/null 2>&1; then
  echo "DEV_HOME ($home) is inside a git repo; OpenCode free models would be hidden. Pick another DEV_HOME." >&2
  exit 1
fi

# Pick the agents' runtime/model lines once, when the config is first created.
write_config() {
  local runtime=${DEV_RUNTIME:-} models=() m1="" m2=""
  if [ -z "$runtime" ]; then
    if command -v opencode >/dev/null 2>&1; then runtime=opencode; else runtime=pi; fi
  fi
  if [ "$runtime" = opencode ]; then
    need opencode "install from https://opencode.ai, or set DEV_RUNTIME=pi|omp"
    local free=() pref=(opencode/nemotron-3-ultra-free opencode/mimo-v2.6-flash-free) m
    # The opencode service may still be starting, so retry before giving up.
    for _ in 1 2 3 4 5; do
      mapfile -t free < <(opencode models 2>/dev/null | grep -E '^opencode/.+-free$' || true)
      [ "${#free[@]}" -gt 0 ] && break
      sleep 2
    done
    # Free models come and go upstream; try the ones that have worked first, then the rest.
    for m in "${pref[@]}"; do [[ " ${free[*]} " == *" $m "* ]] && models+=("$m"); done
    for m in "${free[@]}"; do [[ " ${pref[*]} " == *" $m "* ]] || models+=("$m"); done
    # The sandbox only ever uses free models: never fall back to opencode's (paid) default.
    if [ "${#models[@]}" -eq 0 ]; then
      echo "error: no free opencode/*-free models found; refusing to use opencode's default model. Retry later or set DEV_RUNTIME=pi|omp" >&2
      exit 1
    fi
    m1=${models[0]}; m2=${models[1]:-${models[0]}}
  fi
  line() { # persona-index model
    printf 'runtime = "%s"\n' "$runtime"
    [ -z "$1" ] || printf 'model = "%s"\n' "$1"
  }
  {
    cat <<'EOF'
# Generated by scripts/dev-sandbox.sh. Edit freely; --reset regenerates it.
[runtime]
omp_binary = "omp"
pi_binary = "pi"
prompt_timeout_secs = 300
idle_timeout_secs = 120

[conversation]
reply_order = ["Engineer", "Reviewer"]

[context]
recent_turns = 6
summary_max_tokens = 2000
context_target_tokens = 12000
runtime_rotate_tokens = 150000
summary_refresh_turns = 4

[memory]
mode = "deterministic"

[[personas]]
id = "Engineer"
role = "Software Engineer"
EOF
    line "$m1"
    printf 'system_prompt = "You are the Engineer, a software engineering agent. Reply naturally and concisely."\n'
    printf 'workspace = "%s"\n\n' "$workspace"
    printf '[[personas]]\nid = "Reviewer"\nrole = "Reviewer"\n'
    line "$m2"
    printf 'system_prompt = "You are the Reviewer, a careful reviewer and systems thinker."\n'
    printf 'workspace = "%s"\n\n' "$workspace"
    cat <<'EOF'
[[groups]]
id = "development"
mode = "discussion"
members = ["Engineer", "Reviewer"]
reply_order = ["Reviewer", "Engineer"]
[groups.member_roles]
Engineer = "Backend Engineer"
Reviewer = "Architecture Reviewer"

[[groups]]
id = "review"
mode = "broadcast"
members = ["Reviewer", "Engineer"]
[groups.member_roles]
Reviewer = "Lead Reviewer"
Engineer = "Implementation Reviewer"
EOF
  } > "$config.tmp"
  mv "$config.tmp" "$config"
  echo "created $config (runtime: $runtime${m1:+, models: $m1 / $m2})"
}
[ -f "$config" ] || write_config

if [ "$ui" = 1 ]; then
  echo "sandbox: $home"
  echo ">>> Open the web UI: http://127.0.0.1:$ui_port   (API: http://127.0.0.1:$port, JSON only)"
else
  echo "sandbox: $home  api: http://127.0.0.1:$port (JSON only; no web UI, use without --api-only)"
fi

pids=()
# cargo/bun/npm do not forward signals to their children, so kill whole descendant trees.
killtree() {
  local child
  for child in $(pgrep -P "$1" 2>/dev/null || true); do killtree "$child"; done
  kill "$1" 2>/dev/null || true
}
cleanup() {
  trap - EXIT INT TERM
  for pid in "${pids[@]}"; do killtree "$pid"; done
  wait 2>/dev/null || true
}
trap 'exit 130' INT
trap 'exit 143' TERM
trap cleanup EXIT

if [ -n "${HIVEMIND_BIN:-}" ]; then
  "$HIVEMIND_BIN" --config "$config" serve --port "$port" &
else
  cargo run --locked --quiet -- --config "$config" serve --port "$port" &
fi
pids+=($!)

if [ "$ui" = 1 ]; then
  [ -d frontend/node_modules ] || (cd frontend && "$JS_PM" install)
  (cd frontend && VITE_HIVEMIND_URL="http://127.0.0.1:$port" exec "$JS_PM" run dev -- --port "$ui_port" --strictPort) &
  pids+=($!)
fi

wait -n
