import { expect, test } from "@playwright/test";
import { tmpdir } from "node:os";
import { join } from "node:path";

test.use({ baseURL: "http://127.0.0.1:15175" });

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`issue backlog, discussion, filters, and automated review at ${viewport.width}px`, async ({ page, request }) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
    await page.addInitScript(() => localStorage.setItem("hivemind.first_run_complete", "true"));
    await page.goto("/#/tasks");
    await expect(page).toHaveTitle(/Hivemind/);
    await page.getByRole("button", { name: "New issue" }).click();
    const title = `Automated issue fixture ${viewport.width}`;
    await page.getByLabel("Title", { exact: true }).fill(title);
    await page.getByLabel("Description", { exact: true }).fill("Preserve session handling.");
    await page.getByLabel("Acceptance criteria").fill("The fixture file exists");
    await page.getByLabel("Labels (comma separated)").fill("bug, automation");
    await page.getByRole("dialog", { name: "New issue" }).getByRole("combobox", { name: "Priority", exact: true }).selectOption("high");
    await page.getByLabel("Start automation immediately").uncheck();
    await page.getByRole("button", { name: "Save to backlog" }).click();
    await expect(page.getByRole("heading", { name: title })).toBeVisible();
    await expect(page.locator(".fact").filter({ hasText: "Status" })).toContainText("Backlog");
    const id = decodeURIComponent(new URL(page.url()).hash.split("/").at(-1)!);
    const endpoint = `http://127.0.0.1:17476/api/v1/tasks/${id}`;
    expect((await (await request.get(`${endpoint}/attempts`)).json()).attempts).toHaveLength(0);
    await page.getByLabel("Add a comment").fill("Do not change existing endpoints.");
    await page.getByRole("button", { name: "Comment", exact: true }).click();
    await expect(page.locator(".issue-comment")).toContainText("Do not change existing endpoints.");
    await page.getByRole("button", { name: "Edit issue", exact: true }).click();
    await page.locator(".issue-metadata").getByRole("combobox", { name: "Priority", exact: true }).selectOption("urgent");
    await page.getByRole("button", { name: "Save issue", exact: true }).click();
    await expect(page.locator(".issue-metadata")).toContainText("urgent");
    await page.getByRole("button", { name: "Close dialog" }).click();
    await page.goto("/#/tasks/backlog");
    await page.locator(".ticket-filter-menu > summary").click();
    await page.getByLabel("Search issues").fill(title);
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await page.locator(".issue-filters").getByRole("combobox", { name: "Priority", exact: true }).selectOption("urgent");
    await page.getByLabel("Label", { exact: true }).fill("bug");
    await page.locator(".ticket-filter-menu > summary").click();
    await expect(page.locator(".ticket-row")).toHaveCount(1);
    await expect(page.getByRole("region", { name: "Backlog", exact: true })).toBeVisible();
    const group = page.getByRole("button", { name: /Backlog 1/ });
    await group.click();
    await expect(page.locator(".ticket-row")).toHaveCount(0);
    await group.click();
    await expect(page.locator(".ticket-row")).toHaveCount(1);
    await page.screenshot({ path: join(tmpdir(), `hivemind-ticket-${viewport.width}-list.png`), fullPage: true });
    await page.getByRole("checkbox", { name: "Select Backlog issues" }).check();
    await expect(page.locator(".ticket-bulk")).toContainText("1 selected");
    await page.getByRole("button", { name: "Start automation", exact: true }).click();
    await expect.poll(async () => (await (await request.get(endpoint)).json()).task.task.status, { timeout: 30_000 }).toBe("completed");
    await page.goto("/#/tasks/closed");
    await expect(page.locator(".ticket-row")).toHaveCount(1);
    await expect(page.getByRole("region", { name: "Done", exact: true })).toBeVisible();
    await page.locator(".ticket-row-link").click();
    await page.getByText("Automation details", { exact: true }).click();
    await expect(page.locator(".fact").filter({ hasText: "Status" })).toContainText("Done");
    await expect(page.locator(".issue-timeline")).toContainText("attempt finished");
    await page.reload();
    await expect(page.locator(".issue-comment")).toContainText("Do not change existing endpoints.");
    await page.getByText("Automation details", { exact: true }).click();
    await expect(page.getByText("Automation completed", { exact: false })).toBeVisible();
    const detail = (await (await request.get(endpoint)).json()).task;
    expect(detail.children).toHaveLength(1);
    expect(detail.children[0].owner).toBe("Engineer");
    expect(detail.children[0].reviewer).toBe("Reviewer");
    expect(detail.children[0].status).toBe("completed");
    const childAttempts = (await (await request.get(`http://127.0.0.1:17476/api/v1/tasks/${detail.children[0].id}/attempts`)).json()).attempts;
    expect(childAttempts.map((a: { kind: string }) => a.kind)).toEqual(["work", "review"]);
    await page.getByRole("dialog").evaluate((dialog) => { dialog.scrollTop = 0; });
    await page.screenshot({ path: join(tmpdir(), `hivemind-ticket-${viewport.width}-detail.png`), fullPage: true });
    expect(await page.locator("body").evaluate((body) => body.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
  });
}

for (const viewport of [{ width: 1240, height: 660 }, { width: 390, height: 844 }]) {
  test(`grouped issue navigation and filtering at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    await page.addInitScript(() => localStorage.setItem("hivemind.first_run_complete", "true"));
    const statuses = ["review", "review", "running", "running", "planning", "ready", "submitted", "blocked", "completed", "submitted"];
    const titles = ["Verify session recovery", "Review artifact indexing", "Preserve session handling", "Add task notifications", "Plan workspace cleanup", "Support task dependencies", "Improve error messages", "Confirm deployment target", "Export verification results", "Audit runtime permissions"];
    const tasks = statuses.map((status, index) => ({ id: `tk_mock_${index}`, root_id: `tk_mock_${index}`, parent_id: null, kind: "work", status, paused: index === 9, objective: titles[index], coordinator: "Lead", owner: index % 2 ? "Reviewer" : "Engineer", reviewer: "Reviewer", updated_at: 1782518400, issue: { number: index + 10, priority: index === 2 ? "urgent" : index < 5 ? "high" : "normal", description: "", labels: index === 2 ? ["bug"] : index % 2 ? ["automation"] : ["feature"] } }));
    await page.route("**/api/v1/tasks?*", (route) => {
      const url = new URL(route.request().url());
      const q = url.searchParams.get("q") ?? "";
      const label = url.searchParams.get("label");
      const priority = url.searchParams.get("priority");
      return route.fulfill({ json: { tasks: tasks.filter((t) => (!q || t.objective.toLowerCase().includes(q.toLowerCase())) && (!label || t.issue.labels.includes(label)) && (!priority || t.issue.priority === priority)), next_after: null } });
    });
    await page.goto("/#/tasks");
    await expect(page.locator(".ticket-row")).toHaveCount(8);
    await expect(page.getByRole("region", { name: "In Review", exact: true })).toBeVisible();
    await expect(page.getByRole("region", { name: "In Progress", exact: true })).toBeVisible();
    await expect(page.getByRole("region", { name: "Todo", exact: true })).toBeVisible();
    await page.screenshot({ path: join(tmpdir(), `hivemind-ticket-${viewport.width}-grouped.png`), fullPage: true });
    const nav = viewport.width < 700 ? page.getByRole("navigation", { name: "Issue views" }) : page.locator(".ticket-subnav");
    await nav.getByRole("link", { name: "Backlog", exact: true }).click();
    await expect(page.locator(".ticket-row")).toHaveCount(1);
    await expect(page.locator(".ticket-row")).toContainText("Audit runtime permissions");
    await nav.getByRole("link", { name: "All issues", exact: true }).click();
    await expect(page.locator(".ticket-row")).toHaveCount(10);
    await page.locator(".ticket-filter-menu > summary").click();
    await page.getByRole("combobox", { name: "Assignee", exact: true }).selectOption("Engineer");
    await expect(page.locator(".ticket-row")).toHaveCount(5);
    await page.getByRole("combobox", { name: "Assignee", exact: true }).selectOption("");
    await page.getByLabel("Search issues").fill("Preserve session");
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await expect(page.locator(".ticket-row")).toHaveCount(1);
    await page.getByRole("button", { name: "Clear filters", exact: true }).click();
    await expect(page.locator(".ticket-row")).toHaveCount(10);
    await page.locator(".ticket-filter-menu > summary").click();
    await page.getByRole("button", { name: "New issue", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "New issue" })).toBeVisible();
    await expect(page.getByLabel("Start automation immediately")).not.toBeChecked();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    expect(await page.locator("body").evaluate((body) => body.scrollWidth <= innerWidth)).toBe(true);
  });
}
