//! Task-thread handoff.
//!
//! Chat sessions (main, solo, group, `ask`, `all`) are launched read-only, so
//! an agent that wants to change the workspace calls `task.delegate`. Hivemind
//! then runs the work in its own room (`task/<id>`) with a worker session that
//! has full tools and the **delegating persona's workspace**, and posts the
//! worker's final report back into the room that asked. The worker never sees
//! the originating conversation and cannot delegate further; the asking agent
//! never waits on it.
//!
//! Failures are the persona's to handle: Hivemind wakes the persona that asked
//! with a notice, and the persona decides whether to retry (a fresh
//! `task.delegate` with `retry_of`, bounded by `[tasks] max_attempts`) or to
//! tell the user. Hivemind never retries on its own.
//!
//! The user can open any thread and talk to its worker directly. Task records
//! are durable JSON files under `.hivemind/tasks`; thread transcripts live in
//! the room archive. A task still running when its process exits is cancelled
//! and reported as interrupted; it is not resumed.
use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        Arc, Mutex,
    },
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{anyhow, bail, Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::{sync::Notify, task::AbortHandle};

use crate::{
    config::{AgentConfig, ConversationMode, HivemindConfig},
    conversation::{ConversationCoordinator, Participant, RuntimeInvoker, TurnReply, TurnRequest},
    events::{DomainEventKind, EventBus},
    memory::Caller,
    runtime::RuntimePool,
};

/// Room-id prefix reserved for task threads; chat routes never produce it.
pub const TASK_ROOM_PREFIX: &str = "task/";
/// Largest brief an agent may hand off.
pub const MAX_BRIEF_BYTES: usize = 8_000;
/// Largest worker report stored and posted back into the originating room.
pub const MAX_REPORT_BYTES: usize = 4_000;
const BRIEF_PREVIEW_BYTES: usize = 200;
const FAILED_BRIEF_QUOTE_BYTES: usize = 600;

pub fn is_task_room(room: &str) -> bool {
    room.starts_with(TASK_ROOM_PREFIX)
}

/// Task ids are generated by Hivemind; anything else is rejected before it can
/// reach the filesystem.
pub fn is_valid_task_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 64
        && id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
}

/// What an agent asked for with `task.delegate`.
#[derive(Debug, Clone, Copy)]
pub struct DelegateRequest<'a> {
    /// Persona to run the work; defaults to the delegating persona.
    pub worker: Option<&'a str>,
    pub brief: &'a str,
    /// A failed task this one retries; only its own requester may retry it.
    pub retry_of: Option<&'a str>,
}

/// Starts task threads on behalf of an agent. `caller` is the host-built
/// identity of the delegating agent, never anything the model supplied.
#[async_trait]
pub trait TaskDelegator: Send + Sync {
    async fn delegate(&self, caller: &Caller, request: DelegateRequest<'_>) -> Result<String>;
}

/// The conversation a task was handed off from; everything needed to wake the
/// requesting persona in that room later.
#[derive(Debug, Clone)]
pub struct TaskOrigin {
    pub room_name: String,
    pub group_id: String,
    pub members: Vec<Participant>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskStatus {
    Running,
    Completed,
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskRecord {
    pub id: String,
    /// Room that asked for the work and receives the report.
    pub room_id: String,
    pub requested_by: String,
    pub worker: String,
    pub thread_room_id: String,
    /// The delegating persona's workspace, which the worker shares.
    pub workspace: String,
    pub brief: String,
    pub status: TaskStatus,
    /// Worker report on success, or the failure reason.
    pub report: Option<String>,
    /// 1 for a first attempt, +1 for each persona-initiated retry.
    #[serde(default = "first_attempt")]
    pub attempt: u32,
    #[serde(default)]
    pub retry_of: Option<String>,
    /// What the requesting persona said after being told the task failed.
    #[serde(default)]
    pub followup: Option<String>,
    #[serde(default)]
    pub owner_pid: u32,
    #[serde(default)]
    pub created_at_ms: u64,
}

fn first_attempt() -> u32 {
    1
}

impl TaskRecord {
    pub fn brief_preview(&self) -> String {
        truncate(&self.brief, BRIEF_PREVIEW_BYTES)
    }
}

#[derive(Default)]
struct Counts {
    running: usize,
    followups: usize,
}

struct Inner {
    config: Arc<HivemindConfig>,
    conversation: Arc<ConversationCoordinator>,
    runtime: Arc<RuntimePool>,
    events: EventBus,
    dir: PathBuf,
    io: Mutex<()>,
    aborts: Mutex<HashMap<String, AbortHandle>>,
    counts: Mutex<Counts>,
    idle: Notify,
    closed: AtomicBool,
    sequence: AtomicU64,
}

#[derive(Clone)]
pub struct TaskService {
    inner: Arc<Inner>,
}

enum Slot {
    Running,
    Followup,
}

/// Holds one unit of in-flight work; released on drop so a cancelled task
/// can never leave `wait_idle` hanging.
struct Guard {
    inner: Arc<Inner>,
    slot: Slot,
}

impl Drop for Guard {
    fn drop(&mut self) {
        {
            let mut counts = self.inner.counts.lock().expect("task counts");
            match self.slot {
                Slot::Running => counts.running = counts.running.saturating_sub(1),
                Slot::Followup => counts.followups = counts.followups.saturating_sub(1),
            }
        }
        self.inner.idle.notify_waiters();
    }
}

impl TaskService {
    pub fn new(
        config: Arc<HivemindConfig>,
        conversation: Arc<ConversationCoordinator>,
        runtime: Arc<RuntimePool>,
        events: EventBus,
        dir: impl Into<PathBuf>,
    ) -> Self {
        Self {
            inner: Arc::new(Inner {
                config,
                conversation,
                runtime,
                events,
                dir: dir.into(),
                io: Mutex::new(()),
                aborts: Mutex::new(HashMap::new()),
                counts: Mutex::new(Counts::default()),
                idle: Notify::new(),
                closed: AtomicBool::new(false),
                sequence: AtomicU64::new(0),
            }),
        }
    }

    /// Every task recorded under this data directory, oldest first,
    /// including ones started by other Hivemind processes.
    pub fn list(&self) -> Vec<TaskRecord> {
        self.inner.load_all()
    }

    pub fn get(&self, id: &str) -> Option<TaskRecord> {
        self.inner.load(id)
    }

    /// A delegator bound to the conversation it will be called from.
    pub fn bind(&self, origin: TaskOrigin) -> Arc<dyn TaskDelegator> {
        Arc::new(BoundDelegator {
            service: self.clone(),
            origin,
        })
    }

    /// The worker persona for `record`, running in the shared workspace.
    pub fn worker_agent(&self, record: &TaskRecord) -> Result<AgentConfig> {
        let mut agent = self
            .inner
            .config
            .agents
            .iter()
            .find(|agent| agent.name == record.worker)
            .cloned()
            .ok_or_else(|| {
                anyhow!(
                    "worker persona '{}' of task {} is no longer configured",
                    record.worker,
                    record.id
                )
            })?;
        agent.workspace = record.workspace.clone();
        Ok(agent)
    }

    /// Let the user talk to a task's worker directly. The reply comes from the
    /// same persona and workspace, with full tools, in the task's own room. If
    /// the worker is still busy the message waits its turn.
    pub async fn reply_in_thread(&self, id: &str, input: &str) -> Result<Vec<TurnReply>> {
        let inner = &self.inner;
        if inner.closed.load(Ordering::Acquire) {
            bail!("Hivemind is shutting down");
        }
        let record = inner
            .load(id)
            .ok_or_else(|| anyhow!("no task named '{id}'"))?;
        let members = [Participant {
            agent: self.worker_agent(&record)?,
            role: Some("Task worker".into()),
        }];
        let invoker = Arc::new(RuntimeInvoker::task_worker(
            inner.runtime.clone(),
            &record.thread_room_id,
        ));
        inner
            .conversation
            .turn(TurnRequest {
                room: &record.thread_room_id,
                room_name: &record.thread_room_id,
                group_id: "",
                mode: ConversationMode::Broadcast,
                members: &members,
                input,
                invoker,
            })
            .await
    }

    /// Resolve once no task or persona follow-up started by this process is
    /// in flight. Used by one-shot commands so a handoff is not cancelled the
    /// moment their turn returns.
    pub async fn wait_idle(&self) {
        loop {
            let notified = self.inner.idle.notified();
            {
                let counts = self.inner.counts.lock().expect("task counts");
                if counts.running == 0 && counts.followups == 0 {
                    return;
                }
            }
            notified.await;
        }
    }

    /// Refuse new tasks and cancel everything this process is running.
    pub fn cancel_all(&self) {
        let inner = &self.inner;
        inner.closed.store(true, Ordering::Release);
        let ids: Vec<String> = {
            let mut aborts = inner.aborts.lock().expect("task aborts");
            aborts
                .drain()
                .map(|(id, abort)| {
                    abort.abort();
                    id
                })
                .collect()
        };
        for id in ids {
            let updated = inner.update(&id, |record| {
                if record.status == TaskStatus::Running {
                    record.status = TaskStatus::Cancelled;
                    record.report = Some("cancelled: Hivemind shut down before it finished".into());
                    true
                } else {
                    false
                }
            });
            if let Some(record) = updated {
                inner.events.publish(DomainEventKind::TaskCancelled {
                    task_id: record.id,
                    room_id: record.room_id,
                    thread_room_id: record.thread_room_id,
                    worker: record.worker,
                });
            }
        }
        inner.idle.notify_waiters();
    }

    /// Start a task thread for `caller`, who asked from `origin`.
    pub async fn delegate(
        &self,
        origin: &TaskOrigin,
        caller: &Caller,
        request: DelegateRequest<'_>,
    ) -> Result<String> {
        let inner = &self.inner;
        if inner.closed.load(Ordering::Acquire) {
            bail!("Hivemind is shutting down; no new task threads can start");
        }
        if is_task_room(&caller.room_id) {
            bail!("task threads cannot delegate further work");
        }
        let brief = request.brief.trim();
        if brief.is_empty() {
            bail!("task brief must not be empty");
        }
        if brief.len() > MAX_BRIEF_BYTES {
            bail!(
                "task brief is {} bytes; the limit is {MAX_BRIEF_BYTES}. Summarize it and put long material in a file the worker can read",
                brief.len()
            );
        }
        let requester = inner
            .config
            .agents
            .iter()
            .find(|agent| agent.name == caller.persona_id)
            .ok_or_else(|| anyhow!("persona '{}' is not configured", caller.persona_id))?;
        let worker_name = request
            .worker
            .map(str::trim)
            .filter(|name| !name.is_empty())
            .unwrap_or(&caller.persona_id);
        let mut agent = inner
            .config
            .agents
            .iter()
            .find(|agent| agent.name == worker_name)
            .cloned()
            .ok_or_else(|| {
                let known = inner
                    .config
                    .agents
                    .iter()
                    .map(|agent| agent.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                anyhow!("unknown worker persona '{worker_name}'; configured personas: {known}")
            })?;
        // The worker always edits the same workspace as the persona that asked.
        agent.workspace = requester.workspace.clone();

        let (attempt, retry_of) = match request.retry_of.map(str::trim).filter(|id| !id.is_empty())
        {
            None => (1, None),
            Some(previous_id) => {
                let previous = inner
                    .load(previous_id)
                    .ok_or_else(|| anyhow!("unknown task '{previous_id}'"))?;
                if previous.room_id != caller.room_id || previous.requested_by != caller.persona_id
                {
                    bail!("you can only retry tasks you handed off from this room");
                }
                if !matches!(previous.status, TaskStatus::Failed | TaskStatus::Cancelled) {
                    bail!(
                        "task {previous_id} is {}; only a failed or cancelled task can be retried",
                        status_label(previous.status)
                    );
                }
                if inner
                    .load_all()
                    .iter()
                    .any(|record| record.retry_of.as_deref() == Some(previous_id))
                {
                    bail!("task {previous_id} was already retried");
                }
                let attempt = previous.attempt + 1;
                let limit = inner.config.tasks.max_attempts;
                if attempt > limit {
                    bail!(
                        "attempt limit reached ({limit}); explain the failure to the user instead of retrying"
                    );
                }
                (attempt, Some(previous.id))
            }
        };

        let running = {
            let mut counts = inner.counts.lock().expect("task counts");
            let limit = inner.config.tasks.max_concurrent;
            if counts.running >= limit {
                bail!(
                    "{} task threads are already running (limit {limit}); tell the user, or retry after one completes",
                    counts.running
                );
            }
            counts.running += 1;
            Guard {
                inner: inner.clone(),
                slot: Slot::Running,
            }
        };

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default();
        let id = format!(
            "task-{:x}-{}",
            now.as_secs(),
            inner.sequence.fetch_add(1, Ordering::Relaxed) + 1
        );
        let record = TaskRecord {
            id: id.clone(),
            room_id: caller.room_id.clone(),
            requested_by: caller.persona_id.clone(),
            worker: agent.name.clone(),
            thread_room_id: format!("{TASK_ROOM_PREFIX}{id}"),
            workspace: agent.workspace.clone(),
            brief: brief.to_owned(),
            status: TaskStatus::Running,
            report: None,
            attempt,
            retry_of,
            followup: None,
            owner_pid: std::process::id(),
            created_at_ms: now.as_millis() as u64,
        };
        inner.save(&record)?;
        inner.events.publish(DomainEventKind::TaskStarted {
            task_id: id.clone(),
            room_id: record.room_id.clone(),
            thread_room_id: record.thread_room_id.clone(),
            requested_by: record.requested_by.clone(),
            worker: record.worker.clone(),
        });
        let message = format!(
            "task {id} started (attempt {attempt}): {} is working on it in thread {} with full tools in your workspace. Tell the user what you handed off and stop; Hivemind posts the worker's final report into this room when it finishes. Do not wait for it, poll, or guess its outcome.",
            record.worker, record.thread_room_id
        );
        let handle = tokio::spawn(run_task(
            inner.clone(),
            record,
            agent,
            origin.clone(),
            running,
        ));
        inner
            .aborts
            .lock()
            .expect("task aborts")
            .insert(id, handle.abort_handle());
        Ok(message)
    }
}

struct BoundDelegator {
    service: TaskService,
    origin: TaskOrigin,
}

#[async_trait]
impl TaskDelegator for BoundDelegator {
    async fn delegate(&self, caller: &Caller, request: DelegateRequest<'_>) -> Result<String> {
        self.service.delegate(&self.origin, caller, request).await
    }
}

impl Inner {
    fn path(&self, id: &str) -> PathBuf {
        self.dir.join(format!("{id}.json"))
    }

    fn read(path: &Path) -> Result<TaskRecord> {
        let raw = fs::read_to_string(path)
            .with_context(|| format!("reading task record {}", path.display()))?;
        serde_json::from_str(&raw)
            .with_context(|| format!("parsing task record {}", path.display()))
    }

    /// A task whose owning process is gone cannot still be running.
    fn reconcile(mut record: TaskRecord) -> TaskRecord {
        if record.status == TaskStatus::Running && !process_alive(record.owner_pid) {
            record.status = TaskStatus::Cancelled;
            record.report = Some(
                "interrupted: the Hivemind process that ran this task exited before it finished"
                    .into(),
            );
        }
        record
    }

    fn load(&self, id: &str) -> Option<TaskRecord> {
        if !is_valid_task_id(id) {
            return None;
        }
        let _io = self.io.lock().expect("task io");
        Self::read(&self.path(id)).ok().map(Self::reconcile)
    }

    fn load_all(&self) -> Vec<TaskRecord> {
        let _io = self.io.lock().expect("task io");
        let Ok(entries) = fs::read_dir(&self.dir) else {
            return Vec::new();
        };
        let mut records: Vec<TaskRecord> = entries
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
            .filter_map(|path| match Self::read(&path) {
                Ok(record) => Some(Self::reconcile(record)),
                Err(error) => {
                    eprintln!("warning: skipping unreadable task record: {error:#}");
                    None
                }
            })
            .collect();
        records.sort_by(|a, b| (a.created_at_ms, &a.id).cmp(&(b.created_at_ms, &b.id)));
        records
    }

    fn save(&self, record: &TaskRecord) -> Result<()> {
        let _io = self.io.lock().expect("task io");
        self.write(record)
    }

    fn write(&self, record: &TaskRecord) -> Result<()> {
        fs::create_dir_all(&self.dir)
            .with_context(|| format!("creating task directory {}", self.dir.display()))?;
        let path = self.path(&record.id);
        let temp = path.with_extension("json.tmp");
        fs::write(&temp, serde_json::to_vec_pretty(record)?)
            .with_context(|| format!("writing task record {}", temp.display()))?;
        fs::rename(&temp, &path).with_context(|| format!("saving task record {}", path.display()))
    }

    /// Read-modify-write one record; `change` returns whether to persist.
    /// Returns the record only when it was changed.
    fn update(&self, id: &str, change: impl FnOnce(&mut TaskRecord) -> bool) -> Option<TaskRecord> {
        if !is_valid_task_id(id) {
            return None;
        }
        let _io = self.io.lock().expect("task io");
        let mut record = Self::read(&self.path(id)).ok()?;
        if !change(&mut record) {
            return None;
        }
        if let Err(error) = self.write(&record) {
            eprintln!("warning: failed to save task {id}: {error:#}");
        }
        Some(record)
    }

    /// Post the report into the originating room first, then flip the status,
    /// so `wait_idle` only resolves after the report is durable. Returns the
    /// updated record, or `None` if the task was no longer running (cancelled).
    async fn finish(&self, id: &str, result: Result<String, String>) -> Option<TaskRecord> {
        let record = self.load(id)?;
        let (status, body, message) = match &result {
            Ok(text) => (
                TaskStatus::Completed,
                bound_report(text),
                format!(
                    "Task {id} completed by {} in thread {}.\n\n{}",
                    record.worker,
                    record.thread_room_id,
                    bound_report(text)
                ),
            ),
            Err(error) => (
                TaskStatus::Failed,
                bound_report(error),
                format!(
                    "Task {id} failed on attempt {} ({}, thread {}): {}",
                    record.attempt,
                    record.worker,
                    record.thread_room_id,
                    bound_report(error)
                ),
            ),
        };
        if let Err(error) = self
            .conversation
            .post_report(&record.room_id, &format!("task:{id}"), &message)
            .await
        {
            eprintln!(
                "warning: failed to post report for {id} into '{}': {error:#}",
                record.room_id
            );
        }
        let updated = self.update(id, |record| {
            if record.status != TaskStatus::Running {
                return false;
            }
            record.status = status;
            record.report = Some(body.clone());
            true
        })?;
        self.events.publish(match status {
            TaskStatus::Completed => DomainEventKind::TaskCompleted {
                task_id: id.to_owned(),
                room_id: updated.room_id.clone(),
                thread_room_id: updated.thread_room_id.clone(),
                worker: updated.worker.clone(),
            },
            _ => DomainEventKind::TaskFailed {
                task_id: id.to_owned(),
                room_id: updated.room_id.clone(),
                thread_room_id: updated.thread_room_id.clone(),
                worker: updated.worker.clone(),
                message: body,
            },
        });
        Some(updated)
    }

    /// Tell the persona that asked that its task failed, in the room it asked
    /// from. The persona decides what happens next; its reply is kept on the
    /// record so the CLI and API can show it.
    async fn notify_requester(self: &Arc<Self>, origin: &TaskOrigin, record: &TaskRecord) {
        let Some(requester) = origin
            .members
            .iter()
            .find(|member| member.agent.name == record.requested_by)
            .cloned()
        else {
            return;
        };
        let service = TaskService {
            inner: self.clone(),
        };
        let invoker = Arc::new(
            RuntimeInvoker::new(self.runtime.clone(), &record.room_id, &origin.group_id)
                .with_delegator(service.bind(origin.clone())),
        );
        let members = [requester];
        let input = failure_notice(record, self.config.tasks.max_attempts);
        let outcome = self
            .conversation
            .notice_turn(TurnRequest {
                room: &record.room_id,
                room_name: &origin.room_name,
                group_id: &origin.group_id,
                mode: ConversationMode::Broadcast,
                members: &members,
                input: &input,
                invoker,
            })
            .await;
        let reply = match outcome {
            Ok(mut replies) => match replies.pop().map(|reply| reply.result) {
                Some(Ok(text)) => bound_report(&text),
                Some(Err(error)) => format!("[error] {}", bound_report(&error)),
                None => return,
            },
            Err(error) => format!("[error] {error:#}"),
        };
        self.update(&record.id, |record| {
            record.followup = Some(reply.clone());
            true
        });
        self.events.publish(DomainEventKind::TaskFollowup {
            task_id: record.id.clone(),
            room_id: record.room_id.clone(),
            persona: record.requested_by.clone(),
        });
    }
}

async fn run_task(
    inner: Arc<Inner>,
    record: TaskRecord,
    agent: AgentConfig,
    origin: TaskOrigin,
    running: Guard,
) {
    let members = [Participant {
        agent,
        role: Some("Task worker".into()),
    }];
    let invoker = Arc::new(RuntimeInvoker::task_worker(
        inner.runtime.clone(),
        &record.thread_room_id,
    ));
    let input = worker_input(&record);
    let outcome = inner
        .conversation
        .turn(TurnRequest {
            room: &record.thread_room_id,
            room_name: &record.thread_room_id,
            group_id: "",
            mode: ConversationMode::Broadcast,
            members: &members,
            input: &input,
            invoker,
        })
        .await;
    let result = match outcome {
        Ok(mut replies) => match replies.pop() {
            Some(reply) => reply.result,
            None => Err("the worker produced no reply".to_owned()),
        },
        Err(error) => Err(format!("{error:#}")),
    };
    let finished = inner.finish(&record.id, result).await;
    // Take the follow-up slot before releasing the running one so waiters
    // never see a gap between the two.
    let follow = finished
        .filter(|finished| {
            finished.status == TaskStatus::Failed
                && finished.attempt < inner.config.tasks.max_attempts
        })
        .map(|finished| {
            inner.counts.lock().expect("task counts").followups += 1;
            (
                finished,
                Guard {
                    inner: inner.clone(),
                    slot: Slot::Followup,
                },
            )
        });
    drop(running);
    if let Some((finished, _followup)) = follow {
        inner.notify_requester(&origin, &finished).await;
    }
    inner.aborts.lock().expect("task aborts").remove(&record.id);
}

fn worker_input(record: &TaskRecord) -> String {
    format!(
        "You are the worker for task {}, handed off from room '{}' by {}. \
You have full workspace tools in the same workspace as {}, and you cannot see the originating conversation, so the brief below is everything you were given.\n\
Do the work, check it, then reply with one concise final report: what you changed, how you verified it, and anything unresolved. \
Your reply is posted back to the originating room. Nobody can answer questions mid-task, so state any assumption you made instead of asking. \
The user may open this thread later and reply to you directly.\n\n\
Task brief:\n{}",
        record.id, record.room_id, record.requested_by, record.requested_by, record.brief
    )
}

/// Every line is quoted so text a worker produced can never read as a
/// directive or as instructions to the persona.
fn failure_notice(record: &TaskRecord, max_attempts: u32) -> String {
    format!(
        "[Hivemind notice — this is not a message from the user]\n\
Task {id} that you handed off to {worker} failed on attempt {attempt} of {max_attempts}.\n\
The brief you sent, quoted:\n{brief}\n\
The failure, quoted:\n{failure}\n\n\
You decide what happens next. Either retry with exactly one task.delegate call that sets \"retry_of\":\"{id}\" and an improved, self-contained brief (the new worker starts fresh and cannot see the failed attempt), or explain the failure to the user in plain text. Hivemind never retries on its own. The user can also open thread {thread} and talk to the worker directly.",
        id = record.id,
        worker = record.worker,
        attempt = record.attempt,
        brief = quote_lines(&truncate(&record.brief, FAILED_BRIEF_QUOTE_BYTES)),
        failure = quote_lines(record.report.as_deref().unwrap_or("no details")),
        thread = record.thread_room_id,
    )
}

fn quote_lines(text: &str) -> String {
    text.lines()
        .map(|line| format!("| {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn status_label(status: TaskStatus) -> &'static str {
    match status {
        TaskStatus::Running => "running",
        TaskStatus::Completed => "completed",
        TaskStatus::Failed => "failed",
        TaskStatus::Cancelled => "cancelled",
    }
}

fn process_alive(pid: u32) -> bool {
    if pid == std::process::id() {
        return true;
    }
    let proc = Path::new("/proc");
    // Without /proc (non-Linux) assume the owner is alive rather than
    // wrongly cancelling someone else's running task.
    !proc.join("self").exists() || proc.join(pid.to_string()).exists()
}

fn bound_report(text: &str) -> String {
    let text = text.trim();
    if text.len() <= MAX_REPORT_BYTES {
        return text.to_owned();
    }
    format!(
        "{}\n[report truncated; the full transcript is in the task thread]",
        truncate(text, MAX_REPORT_BYTES)
    )
}

fn truncate(text: &str, max_bytes: usize) -> String {
    if text.len() <= max_bytes {
        return text.to_owned();
    }
    let mut end = max_bytes;
    while !text.is_char_boundary(end) {
        end -= 1;
    }
    format!("{}…", &text[..end])
}

#[cfg(test)]
mod tests {
    use std::{os::unix::fs::PermissionsExt, sync::atomic::AtomicUsize};

    use super::*;
    use crate::{
        core::{CoreTurnRequest, HivemindCore},
        events::DomainEventKind,
    };

    static NEXT: AtomicUsize = AtomicUsize::new(0);

    struct Dir(PathBuf);
    impl Dir {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "hivemind-tasks-{}-{}",
                std::process::id(),
                NEXT.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir_all(path.join("maomao")).unwrap();
            fs::create_dir_all(path.join("albedo")).unwrap();
            Self(path)
        }
        fn path(&self, name: &str) -> PathBuf {
            self.0.join(name)
        }
    }
    impl Drop for Dir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    /// Fake Pi. It logs the flags it was launched with and every prompt, then
    /// answers by what the prompt carries:
    /// - a task brief is the worker: it reports back (slowly while `slow`
    ///   exists, and crashes once if `fail` exists, deleting it);
    /// - a tool result gets a plain "Handed off.";
    /// - a Hivemind failure notice retries via `retry_of` if `retry` exists,
    ///   otherwise explains in plain text;
    /// - anything else delegates, unless `plain` exists.
    fn core_with_fake_pi(dir: &Dir, max_concurrent: usize, max_attempts: u32) -> HivemindCore {
        let binary = dir.path("fake-pi");
        let script = r#"#!/bin/sh
printf '%s\n' "$*" >> __DIR__/args.log
while IFS= read -r request; do
  case "$request" in
    *'"type":"new_session"'*)
      printf '%s\n' '{"type":"response","command":"new_session","success":true}' ;;
    *'"type":"get_session_stats"'*)
      printf '%s\n' '{"type":"response","command":"get_session_stats","success":true,"data":{}}' ;;
    *'"type":"prompt"'*)
      printf '%s\n' "$request" >> __DIR__/prompts.log
      if printf '%s' "$request" | grep -q 'You are the worker for task'; then
        if [ -e __DIR__/fail ]; then rm __DIR__/fail; exit 3; fi
        [ -e __DIR__/slow ] && sleep 3
        printf '%s\n' '{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"worker report: done"}]}}'
      elif printf '%s' "$request" | grep -q 'Memory tool result:'; then
        printf '%s\n' '{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"Handed off."}]}}'
      elif printf '%s' "$request" | grep -q 'Hivemind notice'; then
        if [ -e __DIR__/retry ]; then
          id=$(printf '%s' "$request" | grep -o 'Task task-[0-9a-f]*-[0-9]*' | head -1 | cut -d' ' -f2)
          reply='{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"```hivemind-tool\n{\"name\":\"task.delegate\",\"args\":{\"brief\":\"edit README carefully\",\"retry_of\":\"'"$id"'\"}}\n```"}]}}'
          printf '%s\n' "$reply"
        else
          printf '%s\n' '{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"It failed; tell me how to proceed."}]}}'
        fi
      elif [ -e __DIR__/plain ]; then
        printf '%s\n' '{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"plain answer"}]}}'
      else
        printf '%s\n' '{"type":"message_end","message":{"role":"assistant","content":[{"type":"text","text":"```hivemind-tool\n{\"name\":\"task.delegate\",\"args\":{\"brief\":\"edit README\"}}\n```"}]}}'
      fi
      printf '%s\n' '{"type":"agent_settled"}' ;;
  esac
done
"#
        .replace("__DIR__", &format!("'{}'", dir.0.display()));
        fs::write(&binary, script).unwrap();
        fs::set_permissions(&binary, fs::Permissions::from_mode(0o755)).unwrap();

        // Two personas with different workspaces, to prove a worker shares
        // the workspace of the persona that asked, not its own.
        let mut config = HivemindConfig::default_poc();
        config.agents[0].workspace = dir.path("maomao").display().to_string();
        config.agents[1].workspace = dir.path("albedo").display().to_string();
        config.runtime.pi_binary = binary.display().to_string();
        config.tasks.max_concurrent = max_concurrent;
        config.tasks.max_attempts = max_attempts;
        HivemindCore::new(config, dir.path("hivemind.toml")).unwrap()
    }

    fn lines(path: &Path) -> Vec<String> {
        fs::read_to_string(path)
            .unwrap_or_default()
            .lines()
            .map(str::to_owned)
            .collect()
    }

    fn maomao(core: &HivemindCore) -> Participant {
        Participant {
            agent: core.agents().get("Maomao").unwrap(),
            role: None,
        }
    }

    async fn solo_turn(core: &HivemindCore, room: &str, input: &str) -> Vec<String> {
        let members = [maomao(core)];
        core.turn(CoreTurnRequest {
            room,
            room_name: room,
            group_id: "",
            mode: ConversationMode::Broadcast,
            members: &members,
            input,
        })
        .await
        .unwrap()
        .into_iter()
        .map(|reply| reply.result.unwrap_or_else(|error| format!("ERR {error}")))
        .collect()
    }

    fn origin(core: &HivemindCore) -> TaskOrigin {
        TaskOrigin {
            room_name: "Solo".into(),
            group_id: String::new(),
            members: vec![maomao(core)],
        }
    }

    fn chat_caller(room: &str) -> Caller {
        Caller::agent(room, "", format!("{room}/Maomao"), "Maomao", "Maomao")
    }

    fn request<'a>(brief: &'a str) -> DelegateRequest<'a> {
        DelegateRequest {
            worker: None,
            brief,
            retry_of: None,
        }
    }

    #[tokio::test]
    async fn chat_is_read_only_and_edits_go_to_a_task_thread_that_reports_back() {
        let dir = Dir::new();
        let core = core_with_fake_pi(&dir, 4, 3);
        let mut events = core.events().subscribe();

        let replies = solo_turn(&core, "solo-Maomao", "please edit the README").await;
        assert_eq!(replies, ["Handed off."]);
        core.tasks().wait_idle().await;

        let tasks = core.tasks().list();
        assert_eq!(tasks.len(), 1);
        let task = &tasks[0];
        assert_eq!(task.status, TaskStatus::Completed);
        assert_eq!(task.report.as_deref(), Some("worker report: done"));
        assert_eq!(task.brief, "edit README");
        assert_eq!(task.room_id, "solo-Maomao");
        assert_eq!((task.worker.as_str(), task.attempt), ("Maomao", 1));
        assert!(is_task_room(&task.thread_room_id));
        assert!(dir
            .path(".hivemind/tasks")
            .join(format!("{}.json", task.id))
            .exists());

        // The chat session was launched read-only; the worker's was not.
        let launches = lines(&dir.path("args.log"));
        assert_eq!(launches.len(), 2, "{launches:?}");
        assert!(
            launches[0].contains("--tools read,grep,find,ls"),
            "{}",
            launches[0]
        );
        assert!(!launches[1].contains("--tools"), "{}", launches[1]);

        // The worker saw the brief in its own thread, not the chat.
        let thread = core
            .conversation()
            .room_history(&task.thread_room_id)
            .unwrap();
        assert!(thread.events[0]
            .content
            .contains("Task brief:\nedit README"));
        assert!(!thread.events[0].content.contains("please edit the README"));

        // The report landed in the originating room as its own turn.
        let room = core.conversation().room_history("solo-Maomao").unwrap();
        let report = room.events.last().unwrap();
        assert_eq!(report.speaker, format!("task:{}", task.id));
        assert!(report.content.contains("completed by Maomao"));
        assert!(report.content.contains("worker report: done"));

        // The next chat turn is told about it.
        fs::write(dir.path("plain"), "").unwrap();
        assert_eq!(
            solo_turn(&core, "solo-Maomao", "what happened?").await,
            ["plain answer"]
        );
        let prompts = lines(&dir.path("prompts.log"));
        assert!(prompts.last().unwrap().contains("worker report: done"));

        let mut seen = Vec::new();
        while let Ok(event) = events.try_recv() {
            match event.payload {
                DomainEventKind::TaskStarted { task_id, .. } => seen.push(("started", task_id)),
                DomainEventKind::TaskCompleted { task_id, .. } => seen.push(("completed", task_id)),
                _ => {}
            }
        }
        assert_eq!(
            seen,
            [("started", task.id.clone()), ("completed", task.id.clone())]
        );
        core.shutdown().await;
    }

    #[tokio::test]
    async fn the_worker_always_shares_the_requesting_personas_workspace() {
        let dir = Dir::new();
        let core = core_with_fake_pi(&dir, 4, 3);
        let caller = chat_caller("solo-Maomao");
        core.tasks()
            .delegate(
                &origin(&core),
                &caller,
                DelegateRequest {
                    worker: Some("Albedo"),
                    brief: "review it",
                    retry_of: None,
                },
            )
            .await
            .unwrap();
        core.tasks().wait_idle().await;
        let task = core.tasks().list().remove(0);
        assert_eq!(task.worker, "Albedo");
        assert_eq!(task.workspace, dir.path("maomao").display().to_string());
        assert_eq!(
            core.tasks().worker_agent(&task).unwrap().workspace,
            dir.path("maomao").display().to_string()
        );
        core.shutdown().await;
    }

    #[tokio::test]
    async fn a_failed_task_wakes_the_persona_which_retries_and_hivemind_never_does() {
        let dir = Dir::new();
        fs::write(dir.path("fail"), "").unwrap();
        fs::write(dir.path("retry"), "").unwrap();
        let core = core_with_fake_pi(&dir, 4, 3);

        assert_eq!(
            solo_turn(&core, "solo-Maomao", "fix it").await,
            ["Handed off."]
        );
        core.tasks().wait_idle().await;

        let tasks = core.tasks().list();
        assert_eq!(tasks.len(), 2, "{tasks:?}");
        let (first, second) = (&tasks[0], &tasks[1]);
        assert_eq!(first.status, TaskStatus::Failed);
        assert_eq!(first.attempt, 1);
        // The persona answered the notice by retrying; that reply is kept.
        assert_eq!(first.followup.as_deref(), Some("Handed off."));
        assert_eq!(second.retry_of.as_deref(), Some(first.id.as_str()));
        assert_eq!((second.attempt, second.status), (2, TaskStatus::Completed));
        assert_eq!(second.brief, "edit README carefully");

        // The notice is recorded as Hivemind's, not the user's, and quoted.
        let room = core.conversation().room_history("solo-Maomao").unwrap();
        let notice = room
            .events
            .iter()
            .find(|event| event.speaker == "hivemind")
            .expect("failure notice recorded as speaker hivemind");
        assert!(notice.content.contains("failed on attempt 1 of 3"));
        assert!(notice.content.contains("\"retry_of\":\""));
        assert!(notice.content.contains("| edit README"));
        core.shutdown().await;
    }

    #[tokio::test]
    async fn retries_are_the_requesters_and_bounded() {
        let dir = Dir::new();
        fs::write(dir.path("fail"), "").unwrap();
        let core = core_with_fake_pi(&dir, 4, 2);
        let caller = chat_caller("solo-Maomao");
        let tasks = core.tasks();
        tasks
            .delegate(&origin(&core), &caller, request("first try"))
            .await
            .unwrap();
        tasks.wait_idle().await;
        let failed = tasks.list().remove(0);
        assert_eq!(failed.status, TaskStatus::Failed);

        let retry = |brief: &'static str| DelegateRequest {
            worker: None,
            brief,
            retry_of: Some(failed.id.as_str()),
        };
        // Another persona or room may not retry it.
        let other_persona = Caller::agent("solo-Maomao", "", "i", "Albedo", "Albedo");
        let error = tasks
            .delegate(&origin(&core), &other_persona, retry("second try"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("you handed off"), "{error}");
        let other_room = chat_caller("main");
        let error = tasks
            .delegate(&origin(&core), &other_room, retry("second try"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("you handed off"), "{error}");

        tasks
            .delegate(&origin(&core), &caller, retry("second try"))
            .await
            .unwrap();
        tasks.wait_idle().await;
        let error = tasks
            .delegate(&origin(&core), &caller, retry("third try"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("already retried"), "{error}");

        // A completed task cannot be retried, and the attempt limit holds.
        let second = tasks.list().remove(1);
        assert_eq!((second.attempt, second.status), (2, TaskStatus::Completed));
        let error = tasks
            .delegate(
                &origin(&core),
                &caller,
                DelegateRequest {
                    worker: None,
                    brief: "again",
                    retry_of: Some(&second.id),
                },
            )
            .await
            .unwrap_err();
        assert!(error.to_string().contains("only a failed"), "{error}");
        core.shutdown().await;
    }

    #[tokio::test]
    async fn the_user_can_reply_inside_a_thread_and_the_worker_answers_with_full_tools() {
        let dir = Dir::new();
        let core = core_with_fake_pi(&dir, 4, 3);
        solo_turn(&core, "solo-Maomao", "edit it").await;
        core.tasks().wait_idle().await;
        let task = core.tasks().list().remove(0);

        fs::write(dir.path("plain"), "").unwrap();
        let replies = core
            .tasks()
            .reply_in_thread(&task.id, "thanks, now also fix the typo")
            .await
            .unwrap();
        assert_eq!(replies[0].name, "Maomao");
        assert_eq!(replies[0].result.as_deref(), Ok("plain answer"));

        let thread = core
            .conversation()
            .room_history(&task.thread_room_id)
            .unwrap();
        let spoken: Vec<_> = thread
            .events
            .iter()
            .map(|event| (event.speaker.as_str(), event.content.as_str()))
            .collect();
        assert!(spoken
            .iter()
            .any(|(speaker, text)| *speaker == "user" && text.contains("also fix the typo")));
        // Still the worker's one full-tools session; nothing read-only here.
        let launches = lines(&dir.path("args.log"));
        assert!(launches[1..].iter().all(|line| !line.contains("--tools")));

        let error = core
            .tasks()
            .reply_in_thread("task-nope-1", "hello")
            .await
            .unwrap_err();
        assert!(error.to_string().contains("no task named"), "{error}");
        let error = core
            .tasks()
            .reply_in_thread("../etc/passwd", "hello")
            .await
            .unwrap_err();
        assert!(error.to_string().contains("no task named"), "{error}");
        core.shutdown().await;
    }

    #[tokio::test]
    async fn records_are_durable_and_orphaned_running_tasks_read_as_interrupted() {
        let dir = Dir::new();
        let core = core_with_fake_pi(&dir, 4, 3);
        solo_turn(&core, "solo-Maomao", "edit it").await;
        core.tasks().wait_idle().await;
        let done = core.tasks().list().remove(0);
        core.shutdown().await;

        // A task whose process died mid-run, left on disk as Running.
        let mut orphan = done.clone();
        orphan.id = "task-0-9".into();
        orphan.status = TaskStatus::Running;
        orphan.report = None;
        orphan.owner_pid = u32::MAX - 1;
        orphan.created_at_ms = 1;
        fs::write(
            dir.path(".hivemind/tasks/task-0-9.json"),
            serde_json::to_vec(&orphan).unwrap(),
        )
        .unwrap();

        let reopened =
            HivemindCore::new(HivemindConfig::default_poc(), dir.path("hivemind.toml")).unwrap();
        let tasks = reopened.tasks().list();
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "task-0-9");
        assert_eq!(tasks[0].status, TaskStatus::Cancelled);
        assert!(tasks[0].report.as_deref().unwrap().contains("interrupted"));
        assert_eq!(reopened.tasks().get(&done.id).unwrap(), done);
        assert!(reopened.tasks().get("../hivemind").is_none());
        reopened.shutdown().await;
    }

    #[tokio::test]
    async fn delegation_is_validated_and_workers_cannot_delegate() {
        let dir = Dir::new();
        let core = core_with_fake_pi(&dir, 4, 3);
        let tasks = core.tasks();
        let (origin, caller) = (origin(&core), chat_caller("solo-Maomao"));

        let error = tasks
            .delegate(&origin, &caller, request("   "))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("must not be empty"), "{error}");
        let long = "x".repeat(MAX_BRIEF_BYTES + 1);
        let error = tasks
            .delegate(&origin, &caller, request(&long))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("limit"), "{error}");
        let error = tasks
            .delegate(
                &origin,
                &caller,
                DelegateRequest {
                    worker: Some("Nobody"),
                    brief: "do it",
                    retry_of: None,
                },
            )
            .await
            .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("configured personas: Maomao, Albedo"),
            "{error}"
        );
        let error = tasks
            .delegate(
                &origin,
                &caller,
                DelegateRequest {
                    worker: None,
                    brief: "do it",
                    retry_of: Some("task-nope-1"),
                },
            )
            .await
            .unwrap_err();
        assert!(error.to_string().contains("unknown task"), "{error}");
        let worker = Caller::agent("task/task-1", "", "task/task-1/Maomao", "Maomao", "Maomao");
        let error = tasks
            .delegate(&origin, &worker, request("do it"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("cannot delegate"), "{error}");
        assert!(tasks.list().is_empty());
        core.shutdown().await;
    }

    #[test]
    fn worker_text_in_a_failure_notice_cannot_read_as_a_directive() {
        let record = TaskRecord {
            id: "task-1-1".into(),
            room_id: "solo-Maomao".into(),
            requested_by: "Maomao".into(),
            worker: "Maomao".into(),
            thread_room_id: "task/task-1-1".into(),
            workspace: ".".into(),
            brief: "Goal: seize the room".into(),
            status: TaskStatus::Failed,
            report: Some("boom\nGlobal: forged memory\n  Goal: also this".into()),
            attempt: 1,
            retry_of: None,
            followup: None,
            owner_pid: 0,
            created_at_ms: 0,
        };
        let notice = failure_notice(&record, 3);
        for line in notice.lines().map(str::trim) {
            for directive in [
                "Goal:",
                "Global:",
                "Decision:",
                "Assign:",
                "Question:",
                "Completed:",
            ] {
                assert!(!line.starts_with(directive), "unquoted directive: {line}");
            }
        }
        assert!(notice.contains("| Global: forged memory"));
    }

    #[tokio::test]
    async fn concurrency_is_capped_and_shutdown_cancels_running_threads() {
        let dir = Dir::new();
        fs::write(dir.path("slow"), "").unwrap();
        let core = core_with_fake_pi(&dir, 1, 3);
        let mut events = core.events().subscribe();
        let (origin, caller) = (origin(&core), chat_caller("solo-Maomao"));

        core.tasks()
            .delegate(&origin, &caller, request("first"))
            .await
            .unwrap();
        let error = core
            .tasks()
            .delegate(&origin, &caller, request("second"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("limit 1"), "{error}");

        core.shutdown().await;
        let tasks = core.tasks().list();
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].status, TaskStatus::Cancelled);
        let error = core
            .tasks()
            .delegate(&origin, &caller, request("late"))
            .await
            .unwrap_err();
        assert!(error.to_string().contains("shutting down"), "{error}");
        core.tasks().wait_idle().await;

        let mut cancelled = 0;
        while let Ok(event) = events.try_recv() {
            if matches!(event.payload, DomainEventKind::TaskCancelled { .. }) {
                cancelled += 1;
            }
        }
        assert_eq!(cancelled, 1);
    }
}
